### PR TITLE
fix "Rest arguments don't work with generics"

### LINKED ISSUE #113: Rest arguments don't work with generics
https://jsmonk.github.io/hegel/try#GYVwdgxgLglg9mABAQwDwBUB8AKAdPmKAUwFsBnALkQEEAnW5ATw0wEpEBvAKEUVqKghaSQqTIBuLgF8gA

it reports `Rest argument type should be an array-like` error

### PR DESCRIPTION
**Pull request by thecotne**
fixes #113

### CODE REVIEW

File: packages/core/src/inference/function-type.js [hunk 1]
```diff
@@ -219,10 +219,18 @@ export function inferenceFunctionLiteralType(
...
+                  variant.getRootedSubordinateType().isPrincipalTypeFor(new TypeVar("Array"))
+                )
             )) ||
           paramType instanceof CollectionType ||
-          paramType instanceof TupleType
+          paramType instanceof TupleType ||
+          (
+            paramType instanceof $BottomType &&
+            paramType.getRootedSubordinateType().isPrincipalTypeFor(new TypeVar("Array"))
+          )
```
Comment (thecotne) [inline packages/core/src/inference/function-type.js:233]: @JSMonk  i am not sure if i am doing it correctly but tests are happy with this...

File: packages/core/tests/type-graph.test.js [hunk 2]
```diff
@@ -1362,4 +1362,64 @@ describe("Issues", () => {
        },
     });
   });
+  test("Issue #113: Rest arguments don't work with generics 01", async () => {
+    const sourceAST = prepareAST(`
+      function a<T>(...items: Array<T>) {
```
Comment (munizart) [inline packages/core/tests/type-graph.test.js:1367]: Would it be nice to have a test case for this:
```ts
function a<T, U>(...items: Array<T> | [T, U, T]) {
  return items
}

const arr01: Array<string> = a('str01', 'str03')
const arr02: Array<number> = a(2, false, 3)
const arr03: Array<boolean> = a(false, true, false, true)
```
?

File: packages/core/src/inference/function-type.js (hunk 1 above)
Comment (JSMonk) [reply packages/core/src/inference/function-type.js:233]: Oh, you need to use `CollectionType.Array` Instead of new TypeVar(“Array”)

File: packages/core/tests/type-graph.test.js (hunk 2 above)
Comment (thecotne) [reply packages/core/tests/type-graph.test.js:1367]: that does not type check

return type is `Array<T> | [T, U, T]` and that is not assignable to `Array<T>`

it won't work even without rest args [try](https://hegel.js.org/try#GYVwdgxgLglg9mABAQwDwBUA0iCqA+AChigFMBbAZwC5EBBAJ3uQE8M9EAfRAbS123QBdAJSIA3gChEieiSgh6SYuQoSAvhIkQEFKCkYAGAIw0GTVrvowwAc3YBeFAW4ByS8ZfY3UegYDMLiJaOnrIhgBMpowsqGAgZABGJPQOTtzh2MDIADYUJNh+Qdpguvq+flHmqAlwcNkkyGCpyM5ZufmIPiAdbXnYXSQiQA)

```js
function a<T, U>(items: Array<T> | [T, U, T]) {
  return items
}

const arr01: Array<string> = a(['str01', 'str03'])
const arr02: Array<number> = a([2, false, 3])
const arr03: Array<boolean> = a([false, true, false, true])
```
