### PR TITLE
fix(Issue #100): error processing while statement with logical condition

### LINKED ISSUE #100: Analyzation error:  Cannot read property 'declaration' of undefined
```js
function a(x){}

function test() {
  let id
  while (id === undefined || a(id)) {	}
}
```

### PR DESCRIPTION
**Pull request by srg-kostyrko**
the problem was that if a node had `body` property other properties were not traversed (like `test` in `WhileStatement`)
this fix addresses similar problems in other control structures 

fixes #100

### CODE REVIEW

File: packages/core/src/utils/nodes.js [hunk 1]
```diff
@@ -201,15 +201,15 @@ export const isScopeCreator = (node: Node) =>
     EXPRESSIONS_TYPES.ARROW_FUNCTION_EXPRESSION
   ].includes(node.type);
 
-export const isFunction = (node: Node) =>
-  [
+export const isFunction = (node: ?Node) =>
```
Comment (JSMonk) [inline packages/core/src/utils/nodes.js:204]: Oh, In which cases we can provide `undefined` to `isFunction`?
I think that it's the invalid case when we provide `undefined` as an argument for the function :(

File: packages/core/src/utils/common.js [hunk 2]
```diff
@@ -65,3 +65,7 @@ export function getMemberExressionTarget(node: MemberExpression): Node {
   } while (target.type === NODE.MEMBER_EXPRESSION);
   return target;
 }
+
+export function ensureArray<T>(value: T | Array<T>): Array<T> {
+  return Array.isArray(value) ? value : [value];
```
Comment (JSMonk) [inline packages/core/src/utils/common.js:70]: Can we return an empty Array, if the `value` is `undefined` or `null`? It's micro-optimization, but we will process twice fewer elements for each node 😃

File: packages/core/src/utils/nodes.js (hunk 1 above)
Comment (srg-kostyrko) [reply packages/core/src/utils/nodes.js:204]: it was done to simplify code in getBody
```
...ensureArray(currentNode.arguments).filter(a => !NODE.isFunction(a)),
```
in this line if arguments are empty it will result in array with 1 undefined
so this check in isFunction should prevent it
but I can rework  this to make isFunction always work with values

File: packages/core/src/utils/common.js (hunk 2 above)
Comment (srg-kostyrko) [reply packages/core/src/utils/common.js:70]: yeh good point
this will also allow removing the check in `isFunction` that you commented before
will do

Comment (srg-kostyrko) [reply packages/core/src/utils/common.js:73]: done

File: packages/core/src/utils/common.js [hunk 3]
```diff
@@ -66,6 +66,9 @@ export function getMemberExressionTarget(node: MemberExpression): Node {
   return target;
 }
 
-export function ensureArray<T>(value: T | Array<T>): Array<T> {
+export function ensureArray<T>(value: T | Array<T> | null | undefined): Array<T> {
+  if (value === undefined || value == null) {
```
Comment (JSMonk) [inline packages/core/src/utils/common.js:70]: One more thing, `value == null` convert to `value === null`

Comment (srg-kostyrko) [reply packages/core/src/utils/common.js]: oh mistyped here - fixed

**Comment by JSMonk** [comment]
Thank you a lot. I made a great job :3
