### PR TITLE
Annotate exceptions for packages / standard

### LINKED ISSUE #154: Annotate errors which could be thrown by functions and methods inside "standard library"
Hegel has `$Throws` magic type which helps to annotate which errors can be thrown by ta function.
Some methods and functions from [the standard JavaScript environment](https://github.com/JSMonk/hegel/blob/master/packages/typings/standard/index.d.ts) can throw an error, so the task is to annotate the methods with `$Throws` magic type.
Example:
`JSON.parse` currently has the next method signature:
```typescript
interface JSON {
  // ...
  parse(text: string, reviver?: (this: any, key: string, value: any) => any): unknown;
  // ...
}
```
But, `JSON.parse` throws a `SyntaxError` if the string to parse is not valid JSON .
So, the right signature of the `JSON.parse`  the method should include the `$Throws` magic type:
```typescript
interface JSON {
  // ...
  parse(
    text: string, 
    reviver?: (this: any, key: string, value: any) => any
  ): unknown | $Throws<SyntaxError>;
  // ...
}
```

### PR DESCRIPTION
**Pull request by Demetri0**
This PR resolves #154

### CODE REVIEW

File: packages/typings/standard/index.d.ts [hunk 1]
```diff
@@ -148,13 +148,23 @@ interface Array<T> {
...
-  concat<T1>(...items: Array<T1> | Array<Array<T1>>): Array<T | T1>;
+//  concat<T1>(...items: Array<Array<T1>>): Array<T | T1>;
+  //     /**
+  //       * Combines two or more arrays.
+  //       * @param items Additional items to add to the end of array1.
+  //       */
+//  concat<T1>(...items: Array<T1>): Array<T | T1>;
+  // @throws {TypeError} in case n + len > 2**53 - 1
+  // @throws {RangeError} in case n + len > 2**32 - 1
+  concat<T1>(...items: Array<T1> | Array<Array<T1>>): Array<T | T1> | $Throws<TypeError | RangeError>;
```
Comment (JSMonk) [inline packages/typings/standard/index.d.ts:167]: Please, add the same thing to `ReadonlyArray` :3

**Comment by Demetri0** [comment]
@JSMonk there is probably mistake in `interface BigInt` because of specification of BigInt doesn't contains methods such of `toFixed`, `toExponential`, etc

**Comment by Demetri0** [comment]
Well... I think it is done. Probably I missed something, but it is because I'm not familiar with reading of specification.
While a process, I noticed a lot of missed methods in this d.ts file, probably it will be good to update it with newest specification, but it is job for a new task.
Thank you for patience ^_^
